"""add extracted text to resume

Revision ID: 604b39c23f65
Revises: e1626ebb5f79
Create Date: 2026-09-25 10:08:07.860208
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '604b39c23f65'
down_revision: Union[str, None] = 'e1626ebb5f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('extracted_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'extracted_text')
    # ### end Alembic commands ###