"""add target role to resume

Revision ID: 6430b8f23d38
Revises: 604b39c23f65
Create Date: 2026-09-25 10:46:12.666212
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6430b8f23d38'
down_revision: Union[str, None] = '604b39c23f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('target_role', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'target_role')
    # ### end Alembic commands ###